### ISSUE TITLE
#20 - Reddit feed on the left button menu

### ISSUE THREAD

**Issue by NeverTwice** [adrienpayen/ionic-lab#20]
Put a reddit feed on the left button menu

**Comment by Chateux** [comment]
For reddit, what do you want to do?

**Comment by NeverTwice** [comment]
We'd like to (by clicking the left button on the footer menu) to get a list of subjects referencing (from the most recent) spaceX. Maybe you can get infos about the tags of a subject and select it if spaceX is mentioned. 

When clicking on the link get redirected to the reddit website

**Comment by Chateux** [comment]
Hi,

You can check my pull request : #25

**Comment by NeverTwice** [comment]
I merged it, thanks !
