### ISSUE TITLE
#3 - API Calls

### ISSUE THREAD

**Issue by NeverTwice** [adrienpayen/ionic-lab#3]
- [x] - Get launch information with flight_id
- [x] - Get rocket information with rocket name
- [x] - Get capsule information with capsule name 
- [x] - Get upcoming launches
- [x] - Get past launches (with date param)

**Comment by NeverTwice** [comment]
Great, thanks for the first one. I'll keep you up to date when you'll be able to add the 2 others 👍

**Comment by NeverTwice** [comment]
@Chateux You can go for "Rocket information" as launch detail is ready. There's a "See more" button.

**Comment by NeverTwice** [comment]
I added 2 more to do calls

**Comment by Chateux** [comment]
I will see that thanks you

**Comment by NeverTwice** [comment]
I ended up doing upcoming and past launches. 
There's only one more left to do right now

"Get capsule information with capsule name"

**Comment by Chateux** [comment]
Ok i take this point
